from selenium.webdriver.common.by import By
class MainFunctionalPageLocators:
    designer = (By.XPATH, "//a[contains(@class, 'AppHeader_header__link__3D_hX') and @href='/']")
    order_feed = (By.XPATH, "//li[@class='undefined ml-2']")
    inscription_collect_burger = (By.XPATH, "//h1[@class='text text_type_main-large mb-5 mt-10']")
    inscription_order_feed = (By.XPATH, "//h1[@class='text text_type_main-large mt-10 mb-5']")
    ingridient = (By.XPATH, "//a[contains(@class, 'BurgerIngredient_ingredient__1TVf6') and @href='/ingredient/61c0c5a71d1f82001bdaaa6d']")
    ingridient_card = (By.XPATH, "//div[@class= 'Modal_modal__contentBox__sCy8X pt-10 pb-15']")
    ingridient_card_close_button = (By.XPATH, "//button[@class= 'Modal_modal__close_modified__3V5XS Modal_modal__close__TnseK']")
    ingridient_target=(By.XPATH, "//div[@class='constructor-element constructor-element_pos_top']")
    counter=(By.XPATH, "//a[@href='/ingredient/61c0c5a71d1f82001bdaaa6d']//p[@class='counter_counter__num__3nue1' and text()='0']")
    changed_counter=(By.XPATH, "//a[@href='/ingredient/61c0c5a71d1f82001bdaaa6d']//p[@class='counter_counter__num__3nue1' and text()='2']")
    personal_account_button = (By.LINK_TEXT, "Личный Кабинет")
    input_email_entrance = (By.XPATH, "//input[@class='text input__textfield text_type_main-default' and @type='text']")
    input_password_entrance = (By.XPATH, "//input[@class='text input__textfield text_type_main-default' and @type='password']")
    entrance_button = (By.XPATH,"//button[@class='button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa']")
    list_of_sauces = (By.XPATH, "//span[text()='Соусы']")
    list_of_fillings = (By.XPATH, "//span[text()='Начинки']")
    sauces_ingridient = (By.XPATH, "//a[contains(@class, 'BurgerIngredient_ingredient__1TVf6 ml-4 mr-4 mb-8')and @href='/ingredient/61c0c5a71d1f82001bdaaa72']")
    filling_ingridient = (By.XPATH, "//a[contains(@class, 'BurgerIngredient_ingredient__1TVf6 ml-4 mr-4 mb-8')and @href='/ingredient/61c0c5a71d1f82001bdaaa6f']")
    checkout_button = (By.XPATH, "//button[@class='button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_large__G21Vg']")
    orders_id = (By.XPATH, "//p[@class='undefined text text_type_main-medium mb-15']")