from selenium.webdriver.common.by import By
class OrderFeedPageLocators:
    order_feed = (By.XPATH, "//li[@class='undefined ml-2']")
    order_feed_2 = (By.XPATH, "//a[contains(@class,'AppHeader_header__link__3D_hX') and @href='/feed']")
    input_email_entrance = (By.XPATH, "//input[@class='text input__textfield text_type_main-default' and @type='text']")
    input_password_entrance = (By.XPATH, "//input[@class='text input__textfield text_type_main-default' and @type='password']")
    entrance_button = (By.XPATH,"//button[@class='button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa']")
    list_of_sauces = (By.XPATH, "//span[text()='Соусы']")
    list_of_fillings = (By.XPATH, "//span[text()='Начинки']")
    sauces_ingridient = (By.XPATH, "//a[contains(@class, 'BurgerIngredient_ingredient__1TVf6 ml-4 mr-4 mb-8')and @href='/ingredient/61c0c5a71d1f82001bdaaa72']")
    filling_ingridient = (By.XPATH, "//a[contains(@class, 'BurgerIngredient_ingredient__1TVf6 ml-4 mr-4 mb-8')and @href='/ingredient/61c0c5a71d1f82001bdaaa6f']")
    checkout_button = (By.XPATH,"//button[@class='button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_large__G21Vg']")
    ingridient = (By.XPATH,"//a[contains(@class, 'BurgerIngredient_ingredient__1TVf6') and @href='/ingredient/61c0c5a71d1f82001bdaaa6d']")
    personal_account_button = (By.LINK_TEXT, "Личный Кабинет")
    order = (By.XPATH, "//div[@class='OrderHistory_textBox__3lgbs mb-6']")
    order_info = (By.XPATH, "//div[@class='Modal_orderBox__1xWdi Modal_modal__contentBox__sCy8X p-10']")
    history_orders_button = (By.XPATH, "//a[@class='Account_link__2ETsJ text text_type_main-medium text_color_inactive']")
    order_number = (By.XPATH, "//p[@class='text text_type_digits-default']")
    order_number_from_order_info = (By.XPATH, "//h2[@class='Modal_modal__title_shadow__3ikwq Modal_modal__title__2L34m text text_type_digits-large mb-8']")
    close_button = (By.XPATH, "//button[@class='Modal_modal__close_modified__3V5XS Modal_modal__close__TnseK']")
    number_of_orders_for_all_time = (By.XPATH, "(//p[@class='OrderFeed_number__2MbrQ text text_type_digits-large'])[1]")
    constructor_button = (By.XPATH, "//a[contains(@class, 'AppHeader_header__link__3D_hX') and .//p[text()='Конструктор']]")
    number_of_orders_for_today = (By.XPATH, "(//p[@class='OrderFeed_number__2MbrQ text text_type_digits-large'])[2]")
    list_of_orders_in_work = (By.XPATH, "//ul[@class='OrderFeed_orderListReady__1YFem OrderFeed_orderList__cBvyi']")
    inv_element = (By.CSS_SELECTOR, ".Modal_modal_overlay__x2ZCr")
    ingridient_target = (By.XPATH, "//div[@class='constructor-element constructor-element_pos_top']")
